apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.clusterConfig.utils.kibanadigital.name }}
  namespace: {{ .Values.clusterConfig.ingress.transvers.name }}
  annotations:
    alb.ingress.kubernetes.io/group.name: {{ .Values.clusterConfig.ingress.transvers.name }}
    alb.ingress.kubernetes.io/group.order: '30'
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.clusterConfig.ingress.transvers.services.kibanadigital.certifcat }}
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '120'
    alb.ingress.kubernetes.io/healthcheck-path: /nginx-health
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '50'
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/success-codes: '200'
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/load-balancer-name: transvers


    alb.ingress.kubernetes.io/auth-type: oidc
    alb.ingress.kubernetes.io/auth-session-timeout: '86400'
    alb.ingress.kubernetes.io/auth-session-cookie: AWSELBAuthSessionCookie
    alb.ingress.kubernetes.io/auth-scope: email openid profile
    alb.ingress.kubernetes.io/auth-on-unauthenticated-request: authenticate
    alb.ingress.kubernetes.io/auth-idp-oidc: '{"issuer":{{ https://cognito-idp.eu-west-3.amazonaws.com/eu-west-3_IURfv7Amo","authorizationEndpoint":"https://funecap-digital-prod.auth.eu-west-3.amazoncognito.com/oauth2/authorize","tokenEndpoint":"https://funecap-digital-prod.auth.eu-west-3.amazoncognito.com/oauth2/token","userInfoEndpoint":"https://funecap-digital-prod.auth.eu-west-3.amazoncognito.com/oauth2/userInfo","secretName":"oidc-transvers-secret"}'


spec:
  tls:
    - hosts:
        - {{ .Values.clusterConfig.ingress.transvers.services.kibanadigital.host }}
  rules:
    - host: {{ .Values.clusterConfig.ingress.transvers.services.kibanadigital.host }}
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: kibanadigital-svc
                port:
                  number: 80